### ISSUE TITLE
Redirection mismatch after uploading a file

### ISSUE THREAD

**Issue by Allmoz** [azlux/botamusique#142]
Hi, in DEV when the bot is behind a Nginx proxy pass that goes to 127.0.0.1;XXXX , the URL of the reloaded page, after file ends been uploaded, is also 127.0.0.1:XXXX. Witch is not accessible remotely.

Hugs!

**Comment by TerryGeng** [comment]
Hi, can you please clarify that what is inaccessible? Web interface? Music files?

**Comment by felix91gr** [comment]
I think he refers to something like this:

- You are in the web interface.
- The web interface is behind Nginx. This means that nginx connects to it through `127.0.0.1:port`, and one can connect to it on the internet via a URL that's handled by nginx.
- You upload a song.
- After the song finishes uploading, the website reloads and sends you to `127.0.0.1:port` instead of sending you to the original URL you were in.
- Since this particular `127.0.0.1` address refers to the server's loopback IP, you as a user from the internet cannot possibly find the bot there, because that address is a loopback into your own computer. What you need here instead of being redirected to `127.0.0.1` is to be redirected to the original public URL that's handled by nginx.

Did I describe it well, @Allmoz?
This might be an error on the nginx configuration, although I don't know enough about either nginx nor botamusique to understand if that's really the case.

**Comment by azlux** [comment]
Hi @Allmoz 
Can you add to the issue the `[webinterface]` configuration part you use ?

**Comment by Allmoz** [comment]
Yes,

[webinterface]
enabled = True
listening_addr = 127.0.0.1
is_web_proxified = True
require_auth = True

**Comment by azlux** [comment]
And your nginx config ?
Mine is also behind a nginx. I can compare and maybe create a wiki for that

**Comment by Allmoz** [comment]
server {
    server_name ~^(?<name>omega|alpha|bravo|charlie|delta)\.example\.com$;

    set $botport "8180"; #Default

    if ($name = "alpha" ) {
        set $botport "8181";
    }
    if ($name = "bravo" ) {
        set $botport "8182";
    }
    if ($name = "charlie" ) {
        set $botport "8183";
    }
    if ($name = "delta" ) {
        set $botport "8184";
    }

    location / {
            proxy_pass http://127.0.0.1:$botport;
    }

    location /hidden-files/ {
            internal;
            alias /srv/hidden-files/;
    }

    client_max_body_size 240m;

**Comment by azlux** [comment]
Hi,
Here my config 
```
        location /xana {
                proxy_pass http://10.0.3.2:8181;
                include snippets/proxy;
                proxy_set_header X-Script-Name /xana;
        }

        location /glados {
                proxy_pass http://10.0.3.2:8182;
                include snippets/proxy;
                proxy_set_header X-Script-Name /glados;
        }
```
with `/etc/nginx/snippets/proxy` is
```
include proxy_params;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_http_version 1.1;
port_in_redirect off;
```

I suppose your missing part is `include proxy_params;` how set `X-Real-IP` and `X-Forwarded-For`
I personally use also `X-Script-Name` because I use sub-folder.

**Comment by Allmoz** [comment]
indeed "include proxy_params;" was  the one that made the difference, :D

**Comment by azlux** [comment]
added : https://github.com/azlux/botamusique/wiki/Reverse-proxy-configuration
