### ISSUE TITLE
Shared (or shareable) tag information

### ISSUE THREAD

**Issue by felix91gr** [azlux/botamusique#151]
**Is your feature request related to a problem? Please describe.**

I have 4 (yes 4 :D) bots running in my Mumble, all in the same server with the same, shared audio library.

I like the tagging feature because sometimes we're in the mood of listening to lofi music, acoustic music, piano, chill music, etc; and having tags lets us filter in just the songs that fit the mood that we're in.

However, the fact that the music library is the same for all bots yet the tags are stored locally for each bot, means that we have to tag all the songs 4 separate times. And that later changes on tags need to be propagated as well.

**Describe the solution you'd like**

I'd love it if the tags were stored in such a way that different bots could read and write into the same tag database.

**Describe alternatives you've considered**

I've thought of three ways to achieve this that do not require bots to know of each other directly:

1. **A `tag.db` inside the music library.** This would allow Botamusique to keep the same schema that is currently being in use for the tag library. The reads and writes would have to be different though, because writing would require us to acquire some sort of lock in the file (I don't know if either the filesystem or SQLite do this already). The lock would stop all reads and writes into the file until the transaction is completely checked and commited into the database. I can help with the detailed design if needed!
2. **Editing individual files' tags**. There is an mp3 metadata field that allows us to add 30 characters of text into a song, describing its genre (https://en.wikipedia.org/wiki/ID3, go to "Enhanced TAG"). This field could be interpeted as a list of "tags" in a way. There are two problems with this though: one, metadata format is not consistent across audio formats, and therefore capabilities might not be either. And two, this is a very lax interpretation of "genre", and probably wouldn't be following the spirit of the ID3 standard.
3. Another idea on the same space as (1), but with **lifted restrictions** such as:
    - "Additive writes (appends basically) mean locks are not acquired" or
    - "Locks are individual per row (so different songs are independent)"

**Additional context**

Thank you for your time :)

**Comment by TerryGeng** [comment]
Hi, thanks for your suggestion.

If you look into the code, you will discover that it tags of one file are kept with its library record. (And querying a list of all existed tags is actually iterating over all records XD) I think as long as your 4 bots are sharing the same music library, things will be fine.

Currently it is not possible since the music library table and settings table stays in one db file. The easiest way is separate them into settings.db and music.db, while provide startup options for choosing the path of both dbs. I will do this later.

I think sqlite is thread safe since it will lock itself before a thread modifies itself. Let's just go ahead and see if concurrency will become a problem.
