### ISSUE TITLE
Web assets Node build flow

### ISSUE THREAD

**Issue by TylerVigario** [azlux/botamusique#155]
We should probably address the project structure if we are to implement a Node build flow. As this would require a source folder for all web assets. The built assets can be (automatically) put into the Flask directory structure.

**Here are some tools I believe we would greatly benefit from**

- [**Babel**](https://github.com/babel/babel)
  - Polyfill features that are missing in your target environment
  - Minify JavaScript
- [**Autoprefixer**](https://github.com/postcss/autoprefixer)
  - Add CSS Vendor Prefixes
- [**node-sass**](https://www.npmjs.com/package/node-sass)
  - Compile Sass to CSS (Bootstrap [source](https://github.com/twbs/bootstrap/tree/master/scss))
  - Minify CSS
- [**HTMLMinifier**](https://github.com/kangax/html-minifier)
  - Minify HTML

**Comment by azlux** [comment]
What do you want to accomplish here ? Minimize the css/js ?
Is there are an issue having the css/js into the project directly ?

**Comment by TylerVigario** [comment]
The goal is to have tooling that allows faster forward development.

There are currently no compatibility guarantees (for all the wonderful browsers) and no automated testing.

**Comment by azlux** [comment]
- Babel : this program is a mess, heavy for few things.
- Autoprefixer ,  quite useless with "recent" browser. Css are all well manage now with default calls.
- node-sass : we don't have sass for now, that is a great css improvement, and sass means Ruby (I hate Ruby)
- HTMLMinifier : Simple debug is hard with that.

We have 2 way too drop jquery, don't use it and wait bootstrap drop it in version 4. Or changing the lib to [Bulma](https://github.com/jgthms/bulma)

I understand some basic JS have some bug, but I think it's not a reason to implement heavy lib for that.

**Comment by TylerVigario** [comment]
These are not libraries

**Comment by TylerVigario** [comment]
@azlux What are your concerns of including these things within the project?

**Comment by TerryGeng** [comment]
Personally, I think it good to minimize our js and HTML. Now our floppy is already 36K, but comparing with fontawsome (1.1M), it seems that it doesn't matter anymore.

I think you have made a great point here. However, I think @azlux and I are aiming to keep things simple, since the bot is not so complicated, at least, currently. For me, don't really care about browser compatibility, because it will drive people crazy (alas). I strictly follows MDN, and it works for my Chrome and @azlux 's Firefox.

But as the main developer of the web interface, I do want to try new things, and learn modern Web design workflow (although this is now my major). And maybe @azlux and I need some proof to accept this concept.

I believe it will be of great help if you can try to implement this workflow, or part of it, in a PR. I will seriously review it and have more discussion with @azlux.

Thanks for you help!

**Comment by TerryGeng** [comment]
A charming possibility of having a workflow is, can I include only the icons I used in the js? If it can be achieved, then I can't be more happy!

**Comment by TylerVigario** [comment]
@TerryGeng Thanks for the feedback!

I was able to dig up a way with Font Awesome to subset the icons included with the [Javascript API](https://fontawesome.com/how-to-use/javascript-api/setup/library).

Here is another example, Bootstrap uses Sass for its [source](https://github.com/twbs/bootstrap/tree/master/scss). They include every feature whether we use it or not (including polyfills) in the [compiled files](https://github.com/twbs/bootstrap/tree/master/dist/css). If we use Sass as well we can selectively include only the portions we use.

**Comment by azlux** [comment]
@TylerVigario My current concern is that I don't want to create a big build flow because this project small. I can always deploy a [drone](https://drone.io/) for that but I feel we will use a tank to squash a fly.
About fontawesome, I completely agree we need to do something better, current implementation is heavy for few icons.

**Comment by TylerVigario** [comment]
@azlux Honestly, I feel like CI/CD would be great thing for almost any project. The work for automated testing would pay for itself many times over. Not to mention we could just use [GitHub Actions](https://github.com/features/actions).

**Comment by TerryGeng** [comment]
@TylerVigario Actually @azlux and I are just too busy to get the whole bunch of software development best practice working for this little project.

Building a up-to-date modern automated workflow can certainly benefit those big projects, with tons of webpages and more. (And I bet they won't build serious project on python). But maintaining those workflow, CI/CD stuffs takes time, and for a little project, if we weigh the pros of having these against the benefit we can get from it, maybe it will turn out that we are just... overreacting.

That's my concerns.

**Comment by TylerVigario** [comment]
@TerryGeng I understand you are guys are busy and have other plans that's why I've offered to implement it. I have no problem taking the time to send in a PR, I just don't want to waste my time.

That's my current concern.

**Comment by TerryGeng** [comment]
@TylerVigario The python part, which I have just refactored, I think is designed to be easy to read.
But the js is another case... now the "custom" has 1000+ lines. I think it make sense to divide it up and use more elegant way to refactor the logic inside.

**Comment by TylerVigario** [comment]
@TerryGeng Well without linking a bunch of different files into the HTML (and more than likely polluting the `window` while we are at it) then we should use a bundler for this.

ECMAScript 2015 still not fully supported...
