### ISSUE TITLE
!url, !yplay do not work on "sign in required" (Age restricted) Youtube Videos

### ISSUE THREAD

**Issue by LODerror** [azlux/botamusique#195]
**description**
Using !url, !yplay on age restricted videos ressults in "unable to download [link]. Removed from Library."

**Affected version**
Current

**To Reproduce**
1. type !yplay (with any age restricted video) e.g. https://www.youtube.com/watch?v=zUOh09GoQgk

**Expected behavior**
The download occurs and plays

Anyone else experience this?

**Comment by TerryGeng** [comment]
We are not using the native API from google because it requires us to provide an API key. We just access the google's webpage and use some naive regex trick to get info out of the search result page.

In principle, if we'd like to access youtube with your identity, we can send cookies with our HTTP request. But personally I think this will unnecessarily make things complicated, so I'm against this.

Let me know if other people have more thoughts on this.

**Comment by LODerror** [comment]
That's true - I only made a thread because I couldn't remember if a song I was listening to was always age restricted or not.

The solution for this I think would just be using soundcloud or having local copies.
