### ISSUE TITLE
Avoiding ffmpeg conversion from downloaded audio to MP3

### ISSUE THREAD

**Issue by Gert-dev** [azlux/botamusique#205]
**Is your feature request related to a problem? Please describe.**
Currently, if I understood correctly, botamusique downloads YouTube video's using youtube-dl and asks it to only download the audio stream (e.g. similar to passing `-x`), after which it converts this file into MP3, which it then uses to play inside Mumble. Would it be possible to skip this conversion to MP3 and instead use the existing WebM/M4A (perhaps botamusique can request a specific suitable format)?

The reason for this request is that on my ARM device, the ffmpeg conversion seems to be by far the most expensive operation. The download takes a couple of seconds, after which the conversion can take a minute or more of maxing out a single core, after which playback starts. On my x86 computer, the conversion is much faster.

(This may be due to unsuitable hardware acceleration being available on this device for these formats (e.g. WebM).)

**Describe the solution you'd like**
Skip converting from one audio format to another (e.g. WebM to MP3 or M4A to MP3) and directly read the existing audio file instead.

**Describe alternatives you've considered**
The alternative solution is to leave this as it is.

**Additional context**
This is related to #35, but not quite the same as I'm not asking to not download anything at all, but rather to try and avoid converting.

**Comment by Lartza** [comment]
> (This may be due to unsuitable hardware acceleration being available on this device for these formats (e.g. WebM).)

If you are thinking audio formats have similar specific hardware accelerations like video, that's not really a thing. Also decoding like with video is usually the fast part, and the slow part for ARM is probably MP3. On x86 audio formats generally should use the generic SSE features to accelerate MP3 encoding, and on ARM the similar instructions are called NEON. It's just a slow CPU being slow and possibly Lame MP3 being a notoriously slow library or not getting NEON accelerated.

> Currently, if I understood correctly, botamusique downloads YouTube video's using youtube-dl and asks it to only download the audio stream (e.g. similar to passing -x), after which it converts this file into MP3, which it then uses to play inside Mumble.

Correct. Botamusique does a second conversion live from MP3 to basically WAV when sending the audio.

Now whether you can disable that first conversion... m4a is already mostly supported but I am not sure how WebM Audio handles metadata like title and thumbnails. The initial conversion is configured here https://github.com/azlux/botamusique/blob/0da652da10acaaf8c1bcbfb98fc1fe06e8c89d45/media/url.py#L161-L166 

But in the following parts it's also forced to be written as an mp3 file and then always read as an mp3 file. Beyond that most of the bot should not care since it just throws the file path into the database and then gives that to ffmpeg, apart for the mentioned metadata in case of WebM
https://github.com/azlux/botamusique/blob/0da652da10acaaf8c1bcbfb98fc1fe06e8c89d45/media/url.py#L149 https://github.com/azlux/botamusique/blob/0da652da10acaaf8c1bcbfb98fc1fe06e8c89d45/media/url.py#L48

Making it configurable might be possible, go ahead and try? ;)

**Comment by Gert-dev** [comment]
@Lartza Thanks for the information. I thought maybe some kind of hardware video decoding could be used during the conversion from a video format to an audio format, but I'm not too savvy about this, and am probably wrong.

Also, thanks for the pointers in the code. I'm not too familiar with Python, but did some experimenting and it _seems_ as if WebM "just works". I'm now testing the diff at the bottom, which _seems_ to be working without any problems, and indeed starts much faster on the device with the ARM processor thanks to not doing the ffmpeg conversion.

It may also be possible to request MP3 audio from youtube-dl directly, but I'm not sure if it's not just going to be doing the same thing in the background if the audio cannot be downloaded in that format.

```diff
diff --git a/media/url.py b/media/url.py
index d4d1aa8..48de9ab 100644
--- a/media/url.py
+++ b/media/url.py
@@ -45,7 +45,7 @@ class URLItem(BaseItem):
             self.title = ""
             self.duration = 0
             self.id = hashlib.md5(url.encode()).hexdigest()
-            self.path = var.tmp_folder + self.id + ".mp3"
+            self.path = var.tmp_folder + self.id + ".webm"
             self.thumbnail = ""
             self.keywords = ""
         else:
@@ -146,23 +146,18 @@ class URLItem(BaseItem):
         self.downloading = True
         base_path = var.tmp_folder + self.id
         save_path = base_path + ".%(ext)s"
-        mp3_path = base_path + ".mp3"
+        mp3_path = base_path + ".webm"
 
         # Download only if music is not existed
         self.ready = "preparing"
 
         self.log.info("bot: downloading url (%s) %s " % (self.title, self.url))
         ydl_opts = {
-            'format': 'bestaudio/best',
+            'format': 'bestaudio/webm',
             'outtmpl': save_path,
             'noplaylist': True,
             'writethumbnail': True,
-            'updatetime': False,
-            'postprocessors': [{
-                'key': 'FFmpegExtractAudio',
-                'preferredcodec': 'mp3',
-                'preferredquality': '192'},
-                {'key': 'FFmpegMetadata'}]
+            'updatetime': False
         }
 
         with youtube_dl.YoutubeDL(ydl_opts) as ydl:

```

**Comment by Lartza** [comment]
> I thought maybe some kind of hardware video decoding could be used during the conversion from a video format to an audio format, but I'm not too savvy about this, and am probably wrong.

There is NO video format, you download webm or m4a audio only directly, since it's all handled by DASH in two separate streams from youtube. (since bestaudio/best is used instead of some other format)

> It may also be possible to request MP3 audio from youtube-dl directly, but I'm not sure if it's not just going to be doing the same thing in the background if the audio cannot be downloaded in that format.

Youtube only offers the audio formats they offer, so this is not possible.

<br>
I guess the only issue with your patch is not every video has webm audio, and will fail. Additionally but less importantly it might not be the best quality audio but I'm not sure on that and the difference to m4a should not be huge.

You could just save the file as any format (with bestaudio/best) without an extension, since ffmpeg SHOULD not care what the extension is and instead just rely on what the file actually contains. Alternatively you would need to get the format and determine the extension based on that. I unfortuantely don't have deep knowings of using youtube-dl as a library on how that would work.

**Comment by Gert-dev** [comment]
Thanks for the information. I see now, no video is ever downloaded.

Using no extension could work - see also the updated patch below. This also _appears_ to work fine, but to be sure I'll try running it on my box for a while to test it. I'm also confused about how the following things still work:

* For some videos I see matching JPG images after download, for others I don't. Either way though, the expected image still shows up properly in Mumble on playing, even after restarting the bot.
* `file.py` appears to do some parsing based on extension, but I'm not sure if or when this is used. It appears to have no path for WebM nor for extensionless files - though the latter could perhaps be solved by using the mimetype rather than the extension. Still, covers and titles are showing up properly in Mumble.
* Is the `FFmpegMetadata` post-processor still necessary? I see now that it's a separate post-processor from the MP3 conversion I removed.

I'm clearing the configured cache folder with the audio and image files each time for testing purposes. Are there perhaps other caches I'm not aware of?

```diff
diff --git a/media/url.py b/media/url.py
index d4d1aa8..2aa6d21 100644
--- a/media/url.py
+++ b/media/url.py
@@ -45,7 +45,7 @@ class URLItem(BaseItem):
             self.title = ""
             self.duration = 0
             self.id = hashlib.md5(url.encode()).hexdigest()
-            self.path = var.tmp_folder + self.id + ".mp3"
+            self.path = var.tmp_folder + self.id
             self.thumbnail = ""
             self.keywords = ""
         else:
@@ -145,24 +145,18 @@ class URLItem(BaseItem):
 
         self.downloading = True
         base_path = var.tmp_folder + self.id
-        save_path = base_path + ".%(ext)s"
-        mp3_path = base_path + ".mp3"
+        save_path = base_path
 
         # Download only if music is not existed
         self.ready = "preparing"
 
         self.log.info("bot: downloading url (%s) %s " % (self.title, self.url))
         ydl_opts = {
-            'format': 'bestaudio/best',
-            'outtmpl': save_path,
+            'format': 'bestaudio/m4a',
+            'outtmpl': base_path,
             'noplaylist': True,
             'writethumbnail': True,
-            'updatetime': False,
-            'postprocessors': [{
-                'key': 'FFmpegExtractAudio',
-                'preferredcodec': 'mp3',
-                'preferredquality': '192'},
-                {'key': 'FFmpegMetadata'}]
+            'updatetime': False
         }
 
         with youtube_dl.YoutubeDL(ydl_opts) as ydl:
@@ -180,7 +174,7 @@ class URLItem(BaseItem):
                     self.log.error("bot: download failed with error:\n %s" % error)
 
             if download_succeed:
-                self.path = mp3_path
+                self.path = save_path
                 self.ready = "yes"
                 self.log.info(
                     "bot: finished downloading url (%s) %s, saved to %s." % (self.title, self.url, self.path))
```

Having an extension could also work. I'm also not familiar with the youtube-dl API and it doesn't seem to return the path to the downloaded file at first glance. Another solution may be to do something like `glob.glob(base_path + ".[!jpg]*")[0]` to get whatever file is generated.

This then leaves `URLItem.__init__`, which hardcodes the extension in the path, but appears to also be able to be initialized from a dictionary, which may then need to take this into account, too.

**Comment by TerryGeng** [comment]
Sorry for the late reply. Yes, your idea makes sense to me. Currently, we download the audio and convert it to mp3 format. The usage of mp3 format has some historic reasons (In the past, we didn't have a metadata database so we needed the ID3 tag to keep it).

The parsing in `file.py` is used to extract metadata from audio files. It is bypassed for URLItem.

I have read your patch and it looks good to me. As long as you have tested it, please feel free to submit a pull request so I can get it merged.

**Comment by Gert-dev** [comment]
Hi @TerryGeng and thanks for your response. I've created https://github.com/azlux/botamusique/pull/210 with this patch.
