### ISSUE TITLE
Metadata retrieval?

### ISSUE THREAD

**Issue by DataDropp** [azlux/botamusique#251]
Having the bot files downloaded and the bot reading from a music library is nice and all. But without metadata, such as like album art, artist, etc it's kinda plain.

Could we have the bot hook into [MusicBrainz](https://musicbrainz.org/)?

MusicBrainz allows [self-hosting](https://github.com/linuxserver/docker-musicbrainz) your own MusicBrainz database and having the bot hook into MusicBrainz or a self-hosted instance would be amazing.

**Comment by singpolyma** [comment]
Even just scanning the ogg/id3 tags in the local files would get us much of the way there without a remote DB

**Comment by 1Gigabit** [comment]
@singpolyma I don't think music from youtube-dl for example will contain the metadata already in the files.

**Comment by TerryGeng** [comment]
I don't think this feature request should be directly added to the official release of the bot, since it depends on some specific 3rd-party services and I don't really want to introduce more of them into the bot. 

We have a pending plugin platform PR #228. Maybe a specific plugin can be made to tackle this?
