### ISSUE TITLE
configparser write

### ISSUE THREAD

**Issue by azlux** [azlux/botamusique#27]
Hi @Lartza ,

I have on issue with your commit https://github.com/azlux/botamusique/pull/22 , write volume change into the configuration have side effect.
1. You cannot change the conf while the bot run (We will erase the change on stop). 
2. The write add all non defined value present into the default. This is annoying when you want minimal `configuration.ini` file.

Solution, We need the volume and blacklist user/url into a separated configparser file. (e.g. `tmp.ini`)

**Comment by Lartza** [comment]
1) Did not really even consider this as an issue. It's fairly normal to not be able to edit the configuration of a running program and we don't even have a way to load it on runtime (like a !reload command) so that that would be expected to be allowed. I did consider writing the config the moment it was changed but that wouldn't really change anything in this situation either. The way I see it this is fixed with either of my proposed solutions for the second issue.

2) This I did have some thought about but didn't really consider it an issue. Since you think it is I see two potential solutions.

Keep a minimal and manual user configuration in configuration.user.ini that is loaded third in the initial configuration opening and keep writing to configuration.ini. This does cause .user.ini to override anything that has been saved to configuration.ini, this does cause it to override any volume the bot has saved for instance.

Or keep a minimal configuration file that is loaded second or third, but is written manually without configparser.write with any options that can be changed runtime. Loading it second or third each have their pros and cons.
