### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by azlux** [azlux/botamusique#3]
#### Features
- [x] Next song
- [x] Randomizer
- [x] Graphical interface
- [x] Playlist
- [x] Who add a music

#### Commands with the interface (disabled)
- [x] list
- [x] play
- [x] playfolder
- [x] random

#### Commands by message to the bot
- [x] volume
- [x] next
- [x] stop
- [x] joinme
- [x] go away
- [x] help
- [ ] pause

#### Web Interface (disabled for now)
- [x] Primary functions
- [x] CSS

**Comment by BafDyce** [comment]
Hi there!
A friend of mine and I are also working on features (over at https://github.com/BafDyce/botamusique). For now we are merging our development in our own development branch because we didn't want to annoy you with PRs.

Some of the major changes we implemented so far:
- Play files from local folder
    - Recursively list all files (even if they are in subsubsub-directories)
    - Nicely display the directory structure in the web interface
    - Download button for each folder/file
    - Upload files
    - playback via `!play_file` looks for best match (don't have to enter the entire file name; also case-insensitive)
        - if more than one file matches, the bot replies with a list of all matched files
- `--config` command line parameter
- Some internal changes:
    - Moved argument parsing from `MumbleBot()` to `main()`
    - Moved location of config object from MumbleBot.config to var.config (was necessary due to some other changes)

Also, you can have a look at our [issues](https://github.com/BafDyce/botamusique/issues) to see what we're working on (and plan to work).

My main questions are:
- Would you be interested in merging our changes? Should we make a pull request (once we resolved all merge conflicts with your latest changes)?
- Do you want us to directly create PRs to your repo or should we keep it in ours (for the moment)?

**Comment by azlux** [comment]
Hi,
I didn't saw you working on the project, it's sooo great.
Here my idea
- First we can merge the projects.
- I will continue working on this project.
- I prefer only one repo, it's easier to manage if we are working on the same bot.

>Do you want us to directly create PRs to your repo or should we keep it in ours (for the moment)?
Are you interesting working as collaborators directly on the project ? (instead of PRs)

**Comment by TerryGeng** [comment]
Continue in #91.
