### ISSUE TITLE
A few requests/questions about the usability 

### ISSUE THREAD

**Issue by hamilton5** [azlux/botamusique#310]
1. !version should tell you the buildid, or the specific version you are after, I used the zip dev version.

~~2. If the mumble-server crashes or restarts the bot does not rejoin, the process needs restarted.~~
created a systemd service file for it

3. People sending text messages directly the bot (PM/Whisper) to control it Is not advertised in channel, It might seem erratic to the other uses that don't know whats going on.

4. thumbnail options? on/off, size, webp images don't load I only see jpg files.

and my last question is why I'm getting repeating lines in the terminal/the output. I run the process in a screen session I see duplicate INFO lines a lot, but not all. logfile has the same thing. example:

[Jan 20 22:56:07 INFO] bot: received command "skip" with arguments "" from MYNICK
[Jan 20 22:56:07 INFO] bot: received command "skip" with arguments "" from MYNICK
[Jan 20 22:56:07 INFO] bot: play music [url] Marina and the Diamonds - Immortal (Mewone!, Syberian Beast Remix) (https://www.youtube.com/watch?v=IKFuaExJ-EI) from playlist music
[Jan 20 22:56:07 INFO] bot: play music [url] Marina and the Diamonds - Immortal (Mewone!, Syberian Beast Remix) (https://www.youtube.com/watch?v=IKFuaExJ-EI) from playlist music

**Affected version**
7.2.2 - zip dev version

**Comment by TerryGeng** [comment]
I would suggest you open separate issues next time. But anyway,

1. If you are using the tarball or zip file downloaded from Github, I'm sure it can display the last commit ID in its version, but you must have Git installed otherwise the bot cannot fetch the commit ID.
2. Sometimes the bot rejoins, sometimes it doesn't. This could be a strange bug of PyMumble but I never look into it because my Mumble server never crashes... If you keep experiencing this issue, let us know so we can have a deeper look.
3. The bot selectively posts messages to the channel because it's simply overwhelming. For example, if I'm searching for a song and the bot posts my queries and search results all over the channel, I believe most people would be pissed off. In fact, we even have a silent mode that completely shuts the bot up, which is requested by some people.
4. I don't understand you. I think we save PNG instead.
5. That's the problem with the broken logging system. We have a redirecting mechanism that makes sure the logs going into the file also be printed to stdout but somehow it prints duplicated lines. Most of the time, we don't care much about stdout because that's only helpful when debugging so people didn't complain a lot. We will come up with a fix later. If you insist, I can move it to my priority list.

**Comment by hamilton5** [comment]
Thanks for your time. A lot of this is just curiosity and if it's actually supposed to work this way.

1. I have git installed - git version 2.30.2 but I specifically downloaded from from the link in the quickstart: http://packages.azlux.fr/botamusique/ not github

3. I'm speaking more about when the bot is responding in channel to someone talking to it via direct message(Send Message).. I think if you talk to the bot privately it should only respond privately. I type !skip to the bot privately, users in the channel don't know what happened or why that song stopped abruptly. 

4. I have JPG and WEBP files only, of 38 files never 1 PNG 
![files](https://user-images.githubusercontent.com/2685451/150560803-94cd7650-68e1-4fb9-8c5c-459aeba52b90.jpg)

5. I don't insist, but logfiles half the size and half the writing only seems logical.

**Comment by TerryGeng** [comment]
> 1. I have git installed - git version 2.30.2 but I specifically downloaded from from the link in the quickstart: http://packages.azlux.fr/botamusique/ not github

Oh, it seems that @azlux drops the `.git/` folder in packing the development snapshot. This is something we can fix. Can you start a new issue about this?



> 2\. I'm speaking more about when the bot is responding in channel to someone talking to it via direct message(Send Message).. I think if you talk to the bot privately it should only respond privately. I type !skip to the bot privately, users in the channel don't know what happened or why that song stopped abruptly.

Do you want the bot to announce in the channel when you privately `!skip`-ed or not?



> 3\. I have JPG and WEBP files only, of 38 files never 1 PNG
The bot stores pictures in its database (although we had discussions before and admitted this is a bad practice). I don't recall a place the bot save the pictures. Are you using the youtube-download feature? If that is the case, then these files were created by `ytb-dl`, and you can safely delete them.

**Comment by hamilton5** [comment]
1. I can if you insist.

2. yes I think people should know why it is changing songs, and that someone is controlling it privately.

3. !url and !playlist I assume that is youtube-download? So if it is storing PNG files in a database that still does not explain why they are not displayed in the channel..

**Comment by TerryGeng** [comment]
> 3\. !url and !playlist I assume that is youtube-download? So if it is storing PNG files in a database that still does not explain why they are not displayed in the channel..

Would you also open a separate issue for this with more details?
