### ISSUE TITLE
Token Support

### ISSUE THREAD

**Issue by zelifcam** [azlux/botamusique#37]
Adding the ability for users to pass a token or tokens when authenticating to the mumble server.

**from pymumble API:**
```
main Mumble object
    class Mumble(host, user, port=64738, password='', certfile=None, keyfile=None, reconnect=False, tokens=[], debug=False)
```

**Comment by Lartza** [comment]
I feel like tokens would better fit !joinme since that would move the need
for token handling from bot admin to server users and wouldn't require bot
restarts for new channels or changed tokens. Wouldn't necessarily even have
to store the tokens.

zelifcam <notifications@github.com> kirjoitti ma 21. tammik. 2019 klo 2.27:

**Comment by zelifcam** [comment]
I see your point.  Security reasons, it makes sense.

**Comment by azlux** [comment]
Little summary. You want a command `!joinme <token>`

Az

**Comment by azlux** [comment]
@zelifcam 
to add token on the fly, you need to send an authenticate message.
Same as this one : https://github.com/azlux/pymumble/blob/a3529e14740e73b1c3a81745bd3d522b965a4cbc/pymumble_py3/mumble.py#L152-L158
With only the authenticate.tokens.extend(self.tokens + <new_token>) message

Az

**Comment by azlux** [comment]
Implemented.
Thank @zelifcam for the code.
