### ISSUE TITLE
Radio streaming doesn't seem to work on local mpd http streams

### ISSUE THREAD

**Issue by r3valkyrie** [azlux/botamusique#59]
**Describe the bug**
When attempting to play an mpd http stream from localhost, the bot gets stuck downloading and does not play anything.

**Affected version**
The exact version you're using (git commit id). You should **always** only report bugs which you can reproduce on the latest version (`uif` branch), however **always** state the current commit id here (in case there are new commits between your report and us looking at it)

3ead8562f130510327303f19ed751220c2661446 (master)

**To Reproduce**
1. Launch the bot.
2. Ensure that mpd is streaming to a local http server. (port 8090 in my case)
3. Add the stream url via the !radio command. (!radio http://localhost:8090/mpd.mp3)

**Expected behavior**
The bot should properly play music from the stream.

**Screenshots**
![1](https://user-images.githubusercontent.com/19850559/71770402-22df9080-2efa-11ea-901c-425730f3eff6.png)

**Desktop (please complete the following information):**
 - OS: Archlabs Linux (5.4.6-arch3-1)
 - Browser: Firefox
 - Version 72.0b11

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
There was a point a while back where this actually worked.

I might try PRing a fix for this if I have time.

**Comment by azlux** [comment]
Hi,
Don't you have any line after "Async download next" ?
Is the bot crash/stop or do nothing ?

**Comment by r3valkyrie** [comment]
There's no more after "Async download next". I'm going to enable debug logs and update the post.

**Comment by TerryGeng** [comment]
I think the bot relies on ffmpeg to play the stream. This is also the case for the radio. Sometimes the bot stops just because it fails on fetching the content from the stream.
You may have a try by typing 
`ffmpeg -v warning -nostdin -i http://localhost:8090/mpd.mp3 -ac 1 -f s16le -ar 48000 -`
in the console and see if you can see some gibbersih coming out. If nothing shows up, you should have a look on your local http stream settings.

**Comment by r3valkyrie** [comment]
ffmpeg seems to be working properly.

**Comment by r3valkyrie** [comment]
Turns out it was an oversight in my configuration, not an issue with the bot. Turns out `always_on` and `tags` need to be set to `"yes"`

**Comment by r3valkyrie** [comment]
Ah jeez. So turns out, that configuration change did not solve the issue. It starts playing the radio if MPD gets restarted while the bot is loading the radio channel. I'm gonna leave this open for now and post the ffmpeg debug logs.

**Comment by r3valkyrie** [comment]
https://haste.r3valkyrie.com/abujonoqaf.txt

**Comment by TerryGeng** [comment]
You can see the problem is actually
`[tcp @ 0x55deac911900] Connection attempt to 127.0.0.1 port 8090 failed: Connection refused`
`[tcp @ 0x55deac911900] Connection to tcp://localhost:8090 failed: Connection refused`

What happens to your 8090 port? Did you properly set it up? I'd suggest you look into the logging file of your MPD to see if the http request of ffmpeg gets to your MPD server. Please make sure it is not blocked by your firewall or something.

You can also access `http://localhost:8090/mpd.mp3` into your browser to check whether it can be accessed.

**Comment by r3valkyrie** [comment]
I'll double check iptables and make sure there aren't any rules that would be blocking it. Keep in mind, those messages only showed up after I restarted MPD while the bot was connecting. No output is shown otherwise.

**Comment by r3valkyrie** [comment]
Issue still persists. I'm able to access the http stream through my browser, the bot does not play from it, however.

**Comment by TerryGeng** [comment]
Thanks for trying around. However, since it is not the bot itself who fetches the data from the stream, this is not actually a problem of the bot. The bot just passes the URL of your stream to ffmpeg and let it do the rest. Since ffmpeg would try to connect to 8090 port on your device, and it failed as shown in your log, I suggest you check the log file of your mpd to see whether it can receive the request from ffmpeg properly.

I'm actually curious about your use case. As far as I know, mpd is a music player. However, I think the bot is capable of playing music. Did you set up your mpd server and your bot on different devices?

**Comment by r3valkyrie** [comment]
Same device. It's extremely odd, since this did function perfectly at some point before. Since this isn't an issue with the bot, I'm gonna go ahead and close. I've found a workaround either way.
