### ISSUE TITLE
Optionally remove song from playlist after playback

### ISSUE THREAD

**Issue by Lartza** [azlux/botamusique#79]
**Is your feature request related to a problem? Please describe.**
It seems after the new playlist format was implemented songs are kept in the playlist because it fits a certain different scenario. But if you occasionally just add a single song to the playlist the bot will just keep repeating that song/playlist and needs constant user intervention to manage.

**Describe the solution you'd like**
Have a config option to just pop music from the playlist when the song is finished.

It seems this might cause some issue if just implemented without thought since !stop runs next(), but I'd have to read more into the flow of playback.

In my personal pymumble bot the current track is cleared and lost on !stop and a new is fetched on !play with deque.popleft() but someone could want !play to start the stopped track again. Then again !pause exists too so, it's maybe realistically impossible to please everyone and you just need to choose how !stop works with regards to removing from playlist.

**Comment by TerryGeng** [comment]
If you just want to remove an item safely, you may check out the remove function in the playlist.

I think it make some sense to offer different mode of the playlist. Currently it is repeat itself, maybe I can add one shot mode and pop-after-play mode as you suggested.

**Comment by azlux** [comment]
@TerryGeng I understand @Lartza concerne because my first implementation wasn't repeat the playlist.
`!skip` was like a remove for current music, and finish music was deleted.

Like a real player, maybe we can add a repeat feature like other into the webpage and "cli"
![image](https://user-images.githubusercontent.com/11210117/75339497-ee041000-5890-11ea-88c9-f1c04a9115bb.png)

If enable, the behavior is the current one, if not, the behavior is the previous one.

**Comment by Lartza** [comment]
Repeat or not in a music player usually leaves the playlist intact though, and if it removes songs without repeat enabled it could annoy and/or confuse some users. I'm personally only interested in every song playing once but I can see both being useful features to different users.

**Comment by TerryGeng** [comment]
Hi guys, I just added three different playback mode in the bot. Please have a look on 6a1320f8f95839b6fa168157cc41a296c29a3308.

You can try the command "!mode". The help reads:
_!mode [{mode}] - get or set the playback mode, {mode} should be one of "one-shot" (play the playlist once), "loop" (looping through the playlist), "random" (randomize the playlist)_
In the mode "one-shot", playlist will be discarded once it reaches its end, that's what old user would expect.

I just finished the command. I still need to make it into the database and the web interface. I fixed some strange bugs in the middle. That is: the bot will behave strangly if you remove the last item on the queue while playing it. I hope you guys may help me test it again, in all three modes.

**Comment by TerryGeng** [comment]
@azlux As for the "-1" problem azlux asked in https://github.com/azlux/botamusique/commit/6a1320f8f95839b6fa168157cc41a296c29a330

That is because, at some point when I was refactoring, I cleared the playlist, add files into it, then it started playing the second song, not the first one.

Then I realize that, for an empty playlist, the current_index is 0, if I add some files, playlist is no longer empty and the following lines will execute playlist.next(), and proceed into the second song.

https://github.com/azlux/botamusique/blob/388016a5afcc8bc802c8faebd939cd492cb4518d/mumbleBot.py#L561-L569

The reason that it was fine before was purely because I'm lucky. There should be some tricky threading problem that causes the following part still gave me 0 as next index.

https://github.com/azlux/botamusique/blob/e046162dff5d06ecc6eab39e8432bb4824fe63d0/media/playlist.py#L44-L51

Anyway, use "-1" as current_index when the playlist is initializing is to fix this problem. Jus tto properly distinguish the "0" for an empty list and "0" for a non-empty list.

**Comment by azlux** [comment]
That way, when the bot start for the first time, you need to add a music twice to add it on the playlist.

**Comment by TerryGeng** [comment]
@azlux Well... Anyway the result is, maybe "-1" is not elegant, but it currently works for me. :-)

**Comment by TerryGeng** [comment]
Okay. Done. In 45f6923534a6cc2d68dc967b12a74f649fc24103. Please have a check.

**Comment by Lartza** [comment]
!url crashes the bot, but only in one-shot mode (starting with an empty playlist)
```
Traceback (most recent call last):
  File "mumbleBot.py", line 769, in <module>
    var.botamusique.loop()
  File "mumbleBot.py", line 559, in loop
    if not self.is_pause and var.playlist.next():
  File "/home/lartza/botamusique/media/playlist.py", line 67, in next
    return self[self.current_index]
IndexError: list index out of range
```

**Comment by TerryGeng** [comment]
The icon I made was too ugly. I changed into some task list-like stuff.

**Comment by TerryGeng** [comment]
Wiki page built. https://github.com/azlux/botamusique/wiki/Playback-mode-explained

![Xnip2020-02-27_10-37-23](https://user-images.githubusercontent.com/2306637/75407344-b7d89600-594d-11ea-8002-6c67350b7284.png)

**Comment by Lartza** [comment]
!url twice, !stop, !play, "Invalid index . Use '!queue' to see your playlist.", !queue "Items on the playlist:
1 (url)", !url, !play, bot freezes for a while

Not sure if the two issues are related

**Comment by TerryGeng** [comment]
No... this is just an old bug of the command system. The logic of determining whether parameter is empty is simply wrong.

**Comment by TerryGeng** [comment]
To avoid adding more bugs I think from now on until this release is posted, I will stop adding features and concentrate on debugging.

Thank you guys for finding these bugs :-).

**Comment by Lartza** [comment]
Both crash and invalid index are fine for me now.

Those out of the way I tried my hardest to break one-shot mode and I couldn't do it. Couldn't confuse the bot in any way or to get any new errors while spamming it with various command combinations I could think. I'm sure some user in the future might but it seems fine for now :P

**Comment by azlux** [comment]
> Those out of the way I tried my hardest to break one-shot mode and I couldn't do it. Couldn't confuse the bot in any way or to get any new errors while spamming it with various command combinations I could think. I'm sure some user in the future might but it seems fine for now :P

It's look like @Lartza do a lot of Monkey testing

**Comment by TerryGeng** [comment]
:D
