### ISSUE TITLE
Separate Bot and Web Interface

### ISSUE THREAD

**Issue by TerryGeng** [azlux/botamusique#81]
I was always annoyed by the warning of Flask
```
WARNING: This is a development server. Do not use it in a production deployment.
```

I look up the documentation of Flask, it says it's not a good practice to call app.run() directly. The recommended way is flask cli. 

> It is not recommended to use this function for development with automatic reloading as this is badly supported. Instead you should be using the flask command line script’s run support.

> Do not use run() in a production setting. It is not intended to meet security and performance requirements for a production server. Instead, see [Deployment Options](https://flask.palletsprojects.com/en/1.1.x/deploying/#deployment) for WSGI server recommendations.

I think that makes some sense. Maybe a production-level server is too much for us, but flask cli certainly offers some good-looking 404 page and better debugging support. 

However, if used in this way, the communication of the web interface and the bot won't as smooth as what it is now (sharing tons of global variables), and for this case, a common practice is to build an RPC interface. The result is the web interface can even be separate from the bot.

I think what kind of server app do we need (keep it as what it is now, or using flask cli, or some options introduced in https://flask.palletsprojects.com/en/1.1.x/deploying/wsgi-standalone/ ) is open for discussion. 

Of course, this is just a discussion for future development. This is not related to the version that we are debugging and preparing to release now.

UPDATE:
In page https://flask.palletsprojects.com/en/1.1.x/deploying/wsgi-standalone/, I noticed a solution called Gevent might be the easiest one. The way it works is just
```
from gevent.pywsgi import WSGIServer
from yourapplication import app

http_server = WSGIServer(('', 5000), app)
http_server.serve_forever()
```

**Comment by Lartza** [comment]
The practial reality with the Flask dev server even for a small application I think is we can literally only serve one request at a time, so I don't know how the webinterface handles having even two people use it even for viewing at a time, especially now with Ajax?

Gunicorn is probably the be all end all but would probablly require completely separating the web interface, complicating things in some ways at least even if we can just add it to requirements.txt, unless we somehow run the bot with it too. It's pretty simple and written in Python, I tend to use it for my small stuff since I don't need uWSGI. It's also what you are probably meant to run even with gevent for most applications(or uWSGI maybe) since the gevent WSGI server alone is fairly limited for a larger scale application (https://stackoverflow.com/a/7857201 from the creator of gevent), but gevent alone could be fine for the bot since we expect the bot and webinterface to only work together.

In the end I'm not even sure if gevent alone will even fix the issue of serving just one request since the bot is not asynchronous, or will the bot just constantly block the webinterface, so would it be worth to just get rid of a single error and maybe introducing more problems than it solves. It could still perform better than Flask but I've never used gevent myself.

**Comment by TerryGeng** [comment]
But surprislying, I always use the web interface with my friends (2-3 people) together and it works well. It won't block the bot since it is running in the other thread. But I think there should be some threading problem because it operates the playlist while the bot is fetching songs from it (so does the command interface). I was thinking about adding some locking, but the bot never goes (too) wrong so far.

I think maybe we can just stick to what we are using by now. Azlux has already removed the WARNING message (by directly admitting we are using a development server) so I'm good now :D

**Comment by TerryGeng** [comment]
We decided not to work on it at this stage.
